### ISSUE TITLE
`format` doesn't accept prop updates in certain cases

### ISSUE THREAD

**Issue by stephencookdev** [halt-hammerzeit/input-format#8]
It looks like the `format` prop doesn't actually update if given a template that is larger than the original

E.g. in this CodeSandbox: https://codesandbox.io/s/pwwnpxljrj - checking the tickbox results in the input still being bound to only 1 digit long. However, if you set the `oneLong` state to `false` originally, then there is no issue (presumably since the original template is longer than any subsequent template)

**Comment by catamphetamine** [comment]
Yes, because it's being initialized in the constructor:
https://github.com/catamphetamine/input-format/blob/master/source/react%20input.js#L61
Perhaps you could instead create several `<ReactInput/>`s (with keys, for example) for each case and then render them conditionally.

```js
if (this.state.XXX) {
  return <ReactInput key="input-format-one" format={formatOne} parse={parseOne} .../>
}
else {
  return <ReactInput key="input-format-two" format={formatTwo} parse={parseTwo} .../>
}
```

The `key` is required so that React doesn't treat those `<ReactInput/>`s as equal and doesn't attempt to `diff` one into another.

**Comment by catamphetamine** [comment]
Or maybe I should rewrite it a bit so that it behaves.
I'll see if that can be done.

**Comment by stephencookdev** [comment]
That's what we're doing currently in our workaround :smile: Just using the `template` that we pass to create the `format` and `parse` as the `key`.

And yeah, it should be fairly easy to keep in sync with the prop using the `componentWillReceiveProps` hook. I'm happy to raise a PR for this too, but wouldn't have time until the end of the week

**Comment by catamphetamine** [comment]
I'll release the fixed version tomorrow, I guess

**Comment by catamphetamine** [comment]
I didn't check but I guess the new version is most likely to work now. Reopen otherwise.

0.2.0 / 17.01.2018
==================

  * Removed the exported `InputController` class. If you didn't use the exported `InputController` class before then there's no need to change anything and just upgrade to the latest version. Otherwise use `onChange`, `onPaste`, `onCut`, `onKeyDown` exported functions instead (this has been decided to be simpler).
